production:
  SENTINEL_PORT: 7379
  SENTINEL_CLUSTER_NAME: yotpo-production
  REDIS_CACHING_DB: 12
  REDIS_RESQUE_DB: 1
  FAILOVER_TIMEOUT: 2
  RECONNECT_WAIT: 5
  MAX_RETIES: 5
  SENTINEL_HOSTS: 
  - 10.1.3.76

  - 10.1.1.192

