#### This is not a production file <--> please take a look at chef and deploy.rb#######
defaults: &defaults
  SENTINEL_HOSTS:
  - 127.0.0.1
  SENTINEL_PORT: 26379
  SENTINEL_CLUSTER_NAME: yotpo-development
  REDIS_CACHING_DB: 12
  REDIS_RESQUE_DB: 1
  FAILOVER_TIMEOUT: 2
  RECONNECT_WAIT: 5
  MAX_RETIES: 5
  REDIS_HOST: redis-s01
  REDIS_PORT: 6379

development:
  <<: *defaults

test:
  <<: *defaults
  REDIS_CACHING_DB: 10
  REDIS_RESQUE_DB: 3

staging:
  <<: *defaults
  REDIS_CACHING_DB: 11
  REDIS_RESQUE_DB: 2

production:
  <<: *defaults
  SENTINEL_HOSTS:
  - redis-s01
  SENTINEL_CLUSTER_NAME: yotpo-production
